version: "3"
services:
  service1:
    image: your-docker-registry/service1:latest
    ports:
      - "8081:8080"
  service2:
    image: your-docker-registry/service2:latest
    ports:
      - "8082:8080"

